name: Selenium Tests Suite with Allure Report

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Run Tests
        # Agregamos -DskipTests=false para asegurar ejecución
        run: mvn clean verify
        continue-on-error: true # Permite que el flujo siga aunque un test falle

      - name: Install Allure
        if: always() # Esto asegura que se instale Allure aunque fallen los tests
        run: |
          ALLURE_VERSION=2.24.0
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
          tar -zxvf allure-${ALLURE_VERSION}.tgz
          echo "$PWD/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        if: always() # Genera el reporte siempre
        run: allure generate target/allure-results --clean -o allure-report

      - name: Deploy To GitHub Pages
        if: always() # Sube el reporte siempre
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      - name: Show Allure Report URL
        if: always()
        run: |
          echo "## 🔎 Allure Report" >> $GITHUB_STEP_SUMMARY
          echo "[Ver Reporte](https://santosalan198-glitch.github.io/NopCommerce/)" >> $GITHUB_STEP_SUMMARY